name: csm_client_testing
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  csm_client_core:
    git:
      url: https://github.com/Cosmos-CSM/csm_client
      path: csm_client_core/


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
