name: csm_client_core
description: A CSM package to client implementations.
version: 9.0.0
publish_to: none
repository: https://github.com/RMotive/csm_client_core

environment:
  sdk: ^3.3.3

dependencies:
  http: ^1.2.1
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
